name               'opsworks-cookbooks'
maintainer         'The Authors'
maintainer_email   'you@example.com'
license            'all_rights'
description        'Installs/Configures opsworks-cookbooks'
long_description   'Installs/Configures opsworks-cookbooks'
version            '0.1.0'
depends 'python',  '1.4.6'
depends 'apache2', '3.0.1'
